### PR TITLE
Added Swift Package Manager support.

### PR DESCRIPTION
**Pull request by rokgregoric**
Just add this file .. it works out of the box.

### CODE REVIEW

**Review by afh — CHANGES_REQUESTED** [review]
Looks good overall with a minor comment (see below), thanks @rokgregoric.

We will coordinate merging this PR with a future release to create the necessary tags.

**Review by zoom764 — APPROVED** [review]

**Comment by zoom764** [comment]
Access

**Review by Nanameme10 — APPROVED** [review]

**Comment by lanserxt** [comment]
@afh Hi, sorry any news about that? This is very important for SPM users.

**Comment by afh** [comment]
Thanks for the continued interest, @lanserxt, and emphasizing the importance for folks using Swift Package Manager (SPM). We have started integrating LinkKit via SPM for internal applications to test and verify that things are working as expected. By the looks of things support for SPM will likely come with a future release in the first quarter of 2022.

**Comment by lanserxt** [comment]
@afh Thank you! Currently we have to manually (!) update it every 15th of each month. Since Pods are not available for us. We are so waiting for this. I can even talk to Dave Verwer (https://twitter.com/daveverwer) to include you in Swift Package Index. That will be a big hit for Swift community.

**Comment by lanserxt** [comment]
@afh Sorry, have you agreed on something ?)

**Comment by afh** [comment]
[LinkKit 2.3.2](https://github.com/plaid/plaid-link-ios/releases/tag/2.3.2) adds support for integrating with Swift Package Manager. Please give it a try and report back here (we'll keep this issue open for a couple of days) in case you run into issues or there are questions. We will update the official documentation in the coming days.

@lanserxt I've created SwiftPackageIndex/PackageList#1549 to request inclusion of Plaid LinkKit.

**Comment by rogerluan** [comment]
Looks like this was just released 🎉

**Comment by lanserxt** [comment]
@afh hank you so much! So many things become easier with this improvement. Trying...

**Comment by afh** [comment]
Glad to hear that @lanserxt 🙂

**Comment by lanserxt** [comment]
@afh All went fine on Xcode 13.2.1!

**Comment by afh** [comment]
Thanks for reporting back, @lanserxt, and confirming that integration of LinkKit using Swift Package Manager worked well.

**Comment by pteasima** [comment]
Hey @afh , for me it just says "fetching" forever when I try to add swift package in XCode 13.2.1 

🤷‍♂️ I've tried restarting stuff etc., other packages work for me

**Comment by afh** [comment]
Mind sharing a screenshot, @pteasima, to help understand where exactly it might go wrong?

**Comment by pteasima** [comment]
haha fixed itself 😅. To be fair I did try everything and did try after a little while but still it didn't work and now it does. Thanks anyway.

**Comment by afh** [comment]
Glad to hear that it was fixed @pteasima. Would you please be so kind and share how you fixed your issue in case someone else runs into it?

**Comment by pteasima** [comment]
fixed itself, as I've said. I have to assume github wasn't able to serve the package for the better part of an hour.

**Comment by afh** [comment]
Considering this PR as done as support to integrate LinkKit with Swift Package Manager (SPM) has been added with the [LinkKit 2.3.2](https://github.com/plaid/plaid-link-ios/releases/tag/2.3.2) release, and the [official documentation](https://plaid.com/docs/link/ios/) around LinkKit has been updated accordingly.

In case you are running into issues please [open a new support case from the Plaid dashboard](https://dashboard.plaid.com/support/new).

**Pull request closed without merging**
